name: Approve candidate model
on: [issue_comment]

jobs:
    approve:
        runs-on: ubuntu-latest
        steps:
        - name: ChatOps For Pull Requests
            uses: machine-learning-apps/actions-chatops@1.41
            with:
                APP_PEM: ${{ secrets.APP_PEM }}
                APP_ID: ${{ secrets.APP_ID }}
                TRIGGER_PHRASE: "/lgtm"
                INDICATOR_LABEL: "evaluation complete"
            env:
            GITHUB_TOKEN: ${{ secrets.MLOPS_TUTORIAL_TOKEN }}
            id: prcomm2
        - name: Remove Previous Label
            uses: buildsville/add-remove-label@v1
            with:
                token: ${{secrets.GITHUB_TOKEN}}
                label: evaluation-pending
                type: remove