name: Approve candidate model
on: [issue_comment]

jobs:
  approve:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/lgtm')
    runs-on: ubuntu-latest
    steps:
      - name: ChatOps For Pull Requests
        uses: machine-learning-apps/actions-chatops@1.41
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/lgtm"
          INDICATOR_LABEL: "evaluation-complete"
        env:
          GITHUB_TOKEN: ${{ secrets.MLOPS_TUTORIAL_TOKEN }}
        id: prcomm2
      - uses: actions/checkout@v2
      - name: Remove label
        uses: actions-ecosystem/action-remove-labels@v1.0.0
        with:
          github_token: ${{ secrets.github_token }}
          labels: "evaluation-pending"