name: Deploy to Heroku
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.4.6
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
                heroku_email: "ge02040@hotmail.com"
                usedocker: true
              env: 
                ARTIFACT_LOCATION: "local"

# https://github.com/marketplace/actions/deploy-to-heroku
                