name: Get PR number test
on: [issue_comment]

jobs:
  getpr:
    if: github.event.issue.pull_request != null &&  contains(github.event.comment.body, '/get-pr')
    runs-on: ubuntu-latest
    steps:
      - name: ChatOps For Pull Requests
        uses: machine-learning-apps/actions-chatops@1.41
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/get-pr"
          INDICATOR_LABEL: "test"
        env:
          GITHUB_TOKEN: ${{ secrets.MLOPS_TUTORIAL_TOKEN }}
        id: prcomm

      - uses: actions/github-script@v2
        id: get-pr-number
        with:
          script: |
            const {data: pulls} = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: '${{ github.event.client_payload.ref }}'
            })
            return pulls[0].number
          result-encoding: string
      - run: echo ${{ steps.get-pr-number.outputs.result }}
      - run:   echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        shell: bash
        # Get the PR number for the subsequent comment action
      - uses: actions/checkout@v2.3.2
      - uses: jwalton/gh-find-current-pr@v1.0.2
        id: findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PR is ${PR}"
        env:
            PR: ${{ steps.findPr.outputs.pr }}
      - run: echo "Your PR is ${PULL_NUMBER}"
      - run: echo ${{ github.event.number }}
      - run: echo ${{ github.ref }}
        # if: success() && steps.findPr.outputs.number
        # env:
        #   PR: ${{ steps.findPr.outputs.number }}